config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :credit_cards
  resources :addresses
  resources :customers
  resources :journeys
  resources :cabins
  resources :stations
  resources :trains
  root 'booking_agent#index'

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :street, :city, :postcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :journey
  has_and_belongs_to_many :cabins
  has_many :payments
end

app/models/cabin.rb
class Cabin < ApplicationRecord
  belongs_to :train
  has_and_belongs_to_many :bookings
  validates :beds, :section, :train, presence: true
  
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :customer
  validates :exp_date, :number, :name_on_card, :company, presence: true 

  #attribute to map data values to
  enum company: {
    "American Express" => "AmericanExpress",
    "Visa" => "Visa",
    "MasterCard" => "Mastercard"
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :address
  has_many :credit_cards
  has_many :bookings
  validates :last_name, :first_name, presence: true
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :train
  has_many :bookings
  validates :name, presence: true
  validates :train, presence: true

  #search method used to filter out Journeys
  def self.search(term)
    if term 
      where('name LIKE?', "%#{term}%")
    else 
      all
    end
  end


end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :credit_card
  belongs_to :customer
  belongs_to :booking
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, :town, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :journeys, dependent: :destroy
  validates :name, :capacity, presence: true
end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
  before_action :set_cabin, only: %i[ show edit update destroy ]

  # GET /cabins or /cabins.json
  def index
    @cabins = Cabin.all
  end

  # GET /cabins/1 or /cabins/1.json
  def show
  end

  # GET /cabins/new
  #pulls in train object since cabin references The Trains table - foreign key in cabins table
  def new
    @cabin = Cabin.new
    @trains = Train.all     
  end

  # GET /cabins/1/edit
  #pulls in train object since cabin references The Trains table - foreign key in cabins table
  def edit
    @trains = Train.all   
  end

  # POST /cabins or /cabins.json
  def create
    @cabin = Cabin.new(cabin_params)

    respond_to do |format|
      if @cabin.save
        format.html { redirect_to @cabin, notice: "Cabin was successfully created." }
        format.json { render :show, status: :created, location: @cabin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabins/1 or /cabins/1.json
  def update
    respond_to do |format|
      if @cabin.update(cabin_params)
        format.html { redirect_to @cabin, notice: "Cabin was successfully updated." }
        format.json { render :show, status: :ok, location: @cabin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabins/1 or /cabins/1.json
  def destroy
    @cabin.destroy

    respond_to do |format|
      format.html { redirect_to cabins_url, notice: "Cabin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabin
      @cabin = Cabin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cabin_params
      params.require(:cabin).permit(:name, :beds, :section, :train_id)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[ show edit update destroy ]

  # GET /trains or /trains.json
  def index
    @trains = Train.all    
  end

  # GET /trains/1 or /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains or /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to train_url(@train), notice: "Train was successfully created." }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1 or /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to train_url(@train), notice: "Train was successfully updated." }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1 or /trains/1.json
  def destroy
    @train.destroy

    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Train was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_params
      params.require(:train).permit(:name, :capacity)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_agent_helper.rb
module BookingAgentHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/cabins/_form.html.erb
<%= form_with(model: cabin) do |form| %>
  <% if cabin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cabin.errors.count, "error") %> prohibited this cabin from being saved:</h2>

      <ul>
        <% cabin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :beds %>
    <%= form.number_field :beds %>
  </div>

  <div class="field">
    <%= form.label :section %>
    <%= form.number_field :section %>
  </div>

  <div class="field">
    <%= form.label :train_id, "Train" %>
    <!--allows choice to association of train-->
    <%= form.collection_select :train_id, Train.all, :id, :name, prompt: true %>
    <em><% form.label :train_id %> <br />
    <%= form.collection_radio_buttons( :train_id, Train.all, :id, :name ) %>
    <%#= form.text_field :train_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cabins/edit.html.erb
<h1>Editing Cabin</h1>

<%= render 'form', cabin: @cabin %>

<%= link_to 'Show', @cabin %> |
<%= link_to 'Back', cabins_path %>

app/views/cabins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cabins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Beds</th>
      <th>Section</th>
      <th>Train</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabins.each do |cabin| %>
      <tr>
        <td><%= cabin.name %></td>
        <td><%= cabin.beds %></td>
        <td><%= cabin.section %></td>
        <td><%= cabin.train.name%></td>
        <td><%= link_to 'Show', cabin %></td>
        <td><%= link_to 'Edit', edit_cabin_path(cabin) %></td>
        <td><%= link_to 'Destroy', cabin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cabin', new_cabin_path %>

app/views/cabins/new.html.erb
<h1>New Cabin</h1>

<%= render 'form', cabin: @cabin %>

<%= link_to 'Back', cabins_path %>

app/views/cabins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cabin.name %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @cabin.beds %>
</p>

<p>
  <strong>Section:</strong>
  <%= @cabin.section %>
</p>

<p>
  <strong>Train:</strong>
  <%= @cabin.train.name %>
  <%#= @cabin.train_id %>
</p>

<%= link_to 'Edit', edit_cabin_path(@cabin) %> |
<%= link_to 'Back', cabins_path %>

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
        <% train.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.name %></td>
        <td><%= train.capacity %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @train.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @train.capacity %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>