config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :credit_cards
  resources :addresses
  resources :customers
  resources :journeys
  resources :cabins
  resources :stations
  resources :trains
  root 'booking_agent#index'

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :street, :city, :postcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :journey
  has_and_belongs_to_many :cabins
  has_many :payments
end

app/models/cabin.rb
class Cabin < ApplicationRecord
  belongs_to :train
  has_and_belongs_to_many :bookings
  validates :beds, :section, :train, presence: true
  
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :customer
  validates :exp_date, :number, :name_on_card, :company, presence: true 

  #attribute to map data values to
  enum company: {
    "American Express" => "AmericanExpress",
    "Visa" => "Visa",
    "MasterCard" => "Mastercard"
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :address
  has_many :credit_cards
  has_many :bookings
  validates :last_name, :first_name, presence: true
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :train
  has_many :bookings
  validates :name, presence: true
  validates :train, presence: true

  #search method used to filter out Journeys
  def self.search(term)
    if term 
      where('name LIKE?', "%#{term}%")
    else 
      all
    end
  end


end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :credit_card
  belongs_to :customer
  belongs_to :booking
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, :town, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :journeys, dependent: :destroy
  validates :name, :capacity, presence: true
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hybrid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>    
     <!--Bootstrap cdn-->
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <!-- JavaScript Bundle with Popper -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render './shared/menu' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_menu.html.erb
<p>Find a Cruise | Make a Payment | 
  <%= link_to 'Our Trains', trains_path %> | 
  <%= link_to 'Our Stations', stations_path %> | 
  <%= link_to 'Find a Journey', journeys_path %> |
  <%= link_to 'Find a Customer', customers_path %> | 
  <%= link_to 'Find a Booking', bookings_path %> |
  <%= link_to 'Current Cabins', cabins_path %> |
  <%= link_to 'All Payments', payments_path %> |
  <%= link_to 'Dashboard', root_path %>
</p>