config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :credit_cards
  resources :addresses
  resources :customers
  resources :journeys
  resources :cabins
  resources :stations
  resources :trains
  root 'booking_agent#index'

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :street, :city, :postcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :journey
  has_and_belongs_to_many :cabins
  has_many :payments
end

app/models/cabin.rb
class Cabin < ApplicationRecord
  belongs_to :train
  has_and_belongs_to_many :bookings
  validates :beds, :section, :train, presence: true
  
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :customer
  validates :exp_date, :number, :name_on_card, :company, presence: true 

  #attribute to map data values to
  enum company: {
    "American Express" => "AmericanExpress",
    "Visa" => "Visa",
    "MasterCard" => "Mastercard"
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :address
  has_many :credit_cards
  has_many :bookings
  validates :last_name, :first_name, presence: true
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :train
  has_many :bookings
  validates :name, presence: true
  validates :train, presence: true

  #search method used to filter out Journeys
  def self.search(term)
    if term 
      where('name LIKE?', "%#{term}%")
    else 
      all
    end
  end


end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :credit_card
  belongs_to :customer
  belongs_to :booking
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, :town, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :journeys, dependent: :destroy
  validates :name, :capacity, presence: true
end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
  before_action :set_cabin, only: %i[ show edit update destroy ]

  # GET /cabins or /cabins.json
  def index
    @cabins = Cabin.all
  end

  # GET /cabins/1 or /cabins/1.json
  def show
  end

  # GET /cabins/new
  #pulls in train object since cabin references The Trains table - foreign key in cabins table
  def new
    @cabin = Cabin.new
    @trains = Train.all     
  end

  # GET /cabins/1/edit
  #pulls in train object since cabin references The Trains table - foreign key in cabins table
  def edit
    @trains = Train.all   
  end

  # POST /cabins or /cabins.json
  def create
    @cabin = Cabin.new(cabin_params)

    respond_to do |format|
      if @cabin.save
        format.html { redirect_to @cabin, notice: "Cabin was successfully created." }
        format.json { render :show, status: :created, location: @cabin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabins/1 or /cabins/1.json
  def update
    respond_to do |format|
      if @cabin.update(cabin_params)
        format.html { redirect_to @cabin, notice: "Cabin was successfully updated." }
        format.json { render :show, status: :ok, location: @cabin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabins/1 or /cabins/1.json
  def destroy
    @cabin.destroy

    respond_to do |format|
      format.html { redirect_to cabins_url, notice: "Cabin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabin
      @cabin = Cabin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cabin_params
      params.require(:cabin).permit(:name, :beds, :section, :train_id)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]
  #rescue_from ActiveRecord::RecordNotFound,with: :redirect_if_not_found

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        #creates new address instance, pointing from the customer model with each customer instance having one address
        @customer.create_address!(street: 'the wrong place',
          city: 'someplace', postcode: 'XY1 2YX')
          
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :has_good_credit, :paid)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_agent_helper.rb
module BookingAgentHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :has_good_credit %>
    <%= form.check_box :has_good_credit %>
  </div>

  <div class="field">
    <%= form.label :paid %>
    <%= form.check_box :paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Has good credit</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.last_name %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.has_good_credit %></td>
        <td><%= customer.paid %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Has good credit:</strong>
  <%= @customer.has_good_credit %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @customer.paid %>
</p>

<!--link to edit customer address details-->
<p>
  <b>Address:</b>
  <%= "#{@customer.address.street}" %>
  <%= "#{@customer.address.city}" %>
  <%= "#{@customer.address.postcode}" %><br />
  <%= link_to 'Edit Address', edit_address_path(@customer.address.id) %>
</p>

<p>
  <b>Credit Cards</b>
  <p><%= link_to 'Add a Credit Card', new_credit_card_path(:customer_id => @customer) %></p>
  <hr/>
  <% @customer.credit_cards.each do |cc| %>
    Card Number: <%= cc.number %><br />
    Name on Card: <%= cc.name_on_card %><br />
    Payment Provider: <%= cc.company %><br />
    Expiry Date: <%=cc.exp_date %><br /><br />
     <%= link_to 'Edit Credit Card Details', edit_credit_card_path(cc.id) %><br />
     <hr/>
  <% end %>  
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>