config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :bookings
  resources :credit_cards
  resources :addresses
  resources :customers
  resources :journeys
  resources :cabins
  resources :stations
  resources :trains
  root 'booking_agent#index'

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :street, :city, :postcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :journey
  has_and_belongs_to_many :cabins
  has_many :payments
end

app/models/cabin.rb
class Cabin < ApplicationRecord
  belongs_to :train
  has_and_belongs_to_many :bookings
  validates :beds, :section, :train, presence: true
  
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :customer
  validates :exp_date, :number, :name_on_card, :company, presence: true 

  #attribute to map data values to
  enum company: {
    "American Express" => "AmericanExpress",
    "Visa" => "Visa",
    "MasterCard" => "Mastercard"
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :address
  has_many :credit_cards
  has_many :bookings
  validates :last_name, :first_name, presence: true
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :train
  has_many :bookings
  validates :name, presence: true
  validates :train, presence: true

  #search method used to filter out Journeys
  def self.search(term)
    if term 
      where('name LIKE?', "%#{term}%")
    else 
      all
    end
  end


end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :credit_card
  belongs_to :customer
  belongs_to :booking
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, :town, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :journeys, dependent: :destroy
  validates :name, :capacity, presence: true
end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
  before_action :set_cabin, only: %i[ show edit update destroy ]

  # GET /cabins or /cabins.json
  def index
    @cabins = Cabin.all
  end

  # GET /cabins/1 or /cabins/1.json
  def show
  end

  # GET /cabins/new
  #pulls in train object since cabin references The Trains table - foreign key in cabins table
  def new
    @cabin = Cabin.new
    @trains = Train.all     
  end

  # GET /cabins/1/edit
  #pulls in train object since cabin references The Trains table - foreign key in cabins table
  def edit
    @trains = Train.all   
  end

  # POST /cabins or /cabins.json
  def create
    @cabin = Cabin.new(cabin_params)

    respond_to do |format|
      if @cabin.save
        format.html { redirect_to @cabin, notice: "Cabin was successfully created." }
        format.json { render :show, status: :created, location: @cabin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabins/1 or /cabins/1.json
  def update
    respond_to do |format|
      if @cabin.update(cabin_params)
        format.html { redirect_to @cabin, notice: "Cabin was successfully updated." }
        format.json { render :show, status: :ok, location: @cabin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabins/1 or /cabins/1.json
  def destroy
    @cabin.destroy

    respond_to do |format|
      format.html { redirect_to cabins_url, notice: "Cabin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabin
      @cabin = Cabin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cabin_params
      params.require(:cabin).permit(:name, :beds, :section, :train_id)
    end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :set_journey, only: %i[ show edit update destroy ]
  #before_action :call_train, only: %i[new edit]
   
  # GET /journeys or /journeys.json
  def index
    @journeys = Journey.search(params[:term])      
  end

  # GET /journeys/1 or /journeys/1.json
  def show
  end

  # GET /journeys/new
  #pulls in train object since cabin references The Trains table - foreign key in journey's table
  def new
    @journey = Journey.new
    @trains = Train.all
  end

  # GET /journeys/1/edit
  #pulls in train object since cabin references The Trains table - foreign key in journey's table
  def edit
    @trains = Train.all
  end

  # POST /journeys or /journeys.json
  def create
    @journey = Journey.new(journey_params)

    respond_to do |format|
      if @journey.save
        format.html { redirect_to @journey, notice: "Journey was successfully created." }
        format.json { render :show, status: :created, location: @journey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journeys/1 or /journeys/1.json
  def update
    respond_to do |format|
      if @journey.update(journey_params)
        format.html { redirect_to @journey, notice: "Journey was successfully updated." }
        format.json { render :show, status: :ok, location: @journey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journeys/1 or /journeys/1.json
  def destroy
    @journey.destroy

    respond_to do |format|
      format.html { redirect_to journeys_url, notice: "Journey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journey
      @journey = Journey.find(params[:id])
    end

    def call_train
      @trains = Train.all
    end

    # Only allow a list of trusted parameters through.
    def journey_params
      params.require(:journey).permit(:name, :train_id, :term)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_agent_helper.rb
module BookingAgentHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/journeys/_form.html.erb
<%= form_with(model: journey) do |form| %>
  <% if journey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journey.errors.count, "error") %> prohibited this journey from being saved:</h2>

      <ul>
        <% journey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :train_id %>
    <%#= form.text_field :train_id %>     
    <%= form.collection_radio_buttons(:train_id, Train.all,:id,:name ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journeys/edit.html.erb
<h1>Editing Journey</h1>

<%= render 'form', journey: @journey %>

<%= link_to 'Show', @journey %> |
<%= link_to 'Back', journeys_path %>

app/views/journeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journeys</h1>
<!--Search form-->
<%= form_tag(journeys_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag "Search" %>
<% end %> 

<br />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Train</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journeys.each do |journey| %>
      <tr>
        <td><%= journey.name %></td>
        <td><%= journey.train.name %></td>
        <td><%= link_to 'Show', journey %></td>
        <td><%= link_to 'Edit', edit_journey_path(journey) %></td>
        <td><%= link_to 'Destroy', journey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journey', new_journey_path %>

app/views/journeys/new.html.erb
<h1>New Journey</h1>

<%= render 'form', journey: @journey %>

<%= link_to 'Back', journeys_path %>

app/views/journeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @journey.name %>
</p>

<p>
  <strong>Train:</strong>
  <%= @journey.train.name %>
</p>

<!--looping through the bookings for the customers on the journey-->
<p>
  <% @journey.bookings.each do |booking| 
    @customer = Customer.find(booking.customer_id)
  %>
  <%= @customer.first_name %> <%= @customer.last_name %> booked on <%= booking.created_at %>
</p>
  <% end %>

<%= link_to 'Add a Booking', new_booking_path(:journey_id => @journey) %> |
<%= link_to 'Edit', edit_journey_path(@journey) %> |
<%= link_to 'Back', journeys_path %>